development:
  username: root
  # password: ''
  adapter: mysql2
  encoding: utf8
  database: tdlist-app_rails_development
  pool: 5
  timeout: 5000
  variables:
    sql_mode: TRADITIONAL


test:
  username: root
  # password: ''
  adapter: mysql2
  encoding: utf8
  database: tdlist-app_rails_test
  pool: 5
  timeout: 5000
  variables:
    sql_mode: TRADITIONAL